# Generated by Django 5.0.6 on 2024-07-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='csv')),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Resolved_By', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=50)),
                ('Parent_Record_Type', models.CharField(max_length=50)),
                ('Resolved_DateTime', models.DateTimeField()),
                ('Created_Date_Time', models.DateTimeField()),
            ],
        ),
    ]
