# Generated by Django 5.0.6 on 2024-07-02 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='Created_Date_Time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='Resolved_DateTime',
            field=models.DateField(),
        ),
    ]
